micronaut:
  application:
    name: micronaut-crud
datasources:
  default:
    url: jdbc:mysql://10.11.12.28:3306/mn_playground
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: true
flyway:
  datasources:
    default:
      enabled: true