name: CI - Build and Test

on:

  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:

      - name: Checkout
        uses: actions/checkout@v4


      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21


      - name: Build and test
        run: ./gradlew clean build


      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: micronaut-app-jar
          path: build/libs/*.jar

      - name: Publish to GitHub Packages
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
