name: CI - Build and Test

on:

  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3


      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21


      - name: Build and test
        run: ./gradlew clean build


      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: micronaut-app-jar
          path: build/libs/*.jar
